export interface EvidenceSynthesisTool {
  id: string;
  name: string;
  category: "literature-search" | "text-mining" | "screening" | "data-extraction" | "risk-of-bias" | "reference-management" | "workflow" | "visualization" | "meta-analysis" | "statistics";
  description: string;
  url: string;
  useInSynthesis: boolean;
  useInMetaAnalysis: boolean;
  useInReporting: boolean;
}

export const EVIDENCE_SYNTHESIS_TOOLS: EvidenceSynthesisTool[] = [
  {
    id: "openalex",
    name: "OpenAlex",
    category: "literature-search",
    description: "Open catalog of global research system providing API to retrieve millions of works, authors, and concepts for searching.",
    url: "https://openalex.org/",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: true,
  },
  {
    id: "pubmed-eutilities",
    name: "PubMed E-utilities",
    category: "literature-search",
    description: "NCBI Entrez utilities for automated searches and data retrieval from PubMed.",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK179288/",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: true,
  },
  {
    id: "europe-pmc",
    name: "Europe PMC",
    category: "literature-search",
    description: "Retrieve metadata and full text from Europe PMC database for biomedical literature.",
    url: "https://docs.ropensci.org/europepmc/",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: true,
  },
  {
    id: "citationchaser",
    name: "CitationChaser",
    category: "literature-search",
    description: "Automates backward and forward citation chasing using Lens.org API to find cited and citing papers for systematic reviews.",
    url: "https://estech.shinyapps.io/citationchaser/",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: true,
  },
  {
    id: "litsearchr",
    name: "litsearchr",
    category: "literature-search",
    description: "R package and Shiny app that uses text mining to identify important search terms and build Boolean strings across databases.",
    url: "https://elizagrames.github.io/litsearchr/",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: false,
  },
  {
    id: "prismaid",
    name: "prismAId",
    category: "screening",
    description: "Open-source toolkit designed to support systematic literature reviews using generative AI for structured information extraction.",
    url: "https://prismaid.review",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: false,
  },
  {
    id: "asreview",
    name: "ASReview",
    category: "screening",
    description: "Open-source machine learning tool for systematic reviews that assists researchers in screening papers interactively.",
    url: "https://asreview.ai/",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: false,
  },
  {
    id: "react-extract",
    name: "ReAct-ExtrAct",
    category: "data-extraction",
    description: "Open-source tool for automated, source-grounded data extraction in systematic reviews.",
    url: "https://react-extract.streamlit.app",
    useInSynthesis: true,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "webplotdigitizer",
    name: "WebPlotDigitizer",
    category: "data-extraction",
    description: "Open-source, semi-automated tool to extract numeric data from plot images, useful for meta-analysis.",
    url: "https://apps.automeris.io/wpd/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "metadigitise",
    name: "metaDigitise",
    category: "data-extraction",
    description: "R package for high-throughput, reproducible extraction of data from published figures to digitize plots efficiently.",
    url: "https://cran.r-project.org/web/packages/metaDigitise/index.html",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "survdigitizer",
    name: "SurvdigitizeR",
    category: "data-extraction",
    description: "R package and Shiny application for automated survival curve digitization with accuracy comparable to manual methods.",
    url: "https://pechlilab.shinyapps.io/SurvdigitizeR/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "robotreviewer",
    name: "RobotReviewer",
    category: "risk-of-bias",
    description: "Open-source system that automates risk-of-bias assessment and data extraction for RCTs using NLP.",
    url: "https://www.robotreviewer.net",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: true,
  },
  {
    id: "robvis",
    name: "robvis",
    category: "risk-of-bias",
    description: "R package and web app for generating risk-of-bias assessment plots, supporting RoB2, ROBINS-I, QUADAS-2, and more.",
    url: "https://www.riskofbias.info/welcome/robvis-visualization-tool",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: true,
  },
  {
    id: "critiplot",
    name: "Critiplot",
    category: "risk-of-bias",
    description: "Specialized open-source tool for generating traffic light plots for MMAT, ROBIS, GRADE, NOS, JBI assessments.",
    url: "https://critiplot.vercel.app",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: true,
  },
  {
    id: "dedupe",
    name: "Dedupe",
    category: "reference-management",
    description: "Python library for fast, scalable fuzzy matching and deduplication of records (e.g., citations).",
    url: "https://docs.dedupe.io/en/latest/",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: false,
  },
  {
    id: "litllms",
    name: "LitLLMs",
    category: "text-mining",
    description: "Open-source framework for applying large language models to literature review tasks, including summarization, retrieval, and synthesis.",
    url: "https://litllm.github.io",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: false,
  },
  {
    id: "metanlp",
    name: "MetaNLP",
    category: "text-mining",
    description: "Natural language processing for meta-analysis, processing titles and abstracts for data extraction and synthesis.",
    url: "https://cran.r-project.org/package=MetaNLP",
    useInSynthesis: true,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "robust-lit-review",
    name: "Robust Literature Review",
    category: "workflow",
    description: "Automated systematic literature review pipeline with PRISMA 2020 compliance, DOI validation, grade judge, claim decomposer, semantic selector, crosscheck, and manuscript generation for PubMed/Scopus/Embase.",
    url: "https://github.com/htlin222/robust-lit-review",
    useInSynthesis: true,
    useInMetaAnalysis: true,
    useInReporting: true,
  },
  {
    id: "prisma2020",
    name: "PRISMA 2020 Flow Diagram",
    category: "workflow",
    description: "Official Prisma 2020 Flow Diagram Generator (Shiny App & R package) for correctly formatted PRISMA flow diagrams.",
    url: "https://estech.shinyapps.io/PRISMA_flowdiagram_latest/",
    useInSynthesis: false,
    useInMetaAnalysis: false,
    useInReporting: true,
  },
  {
    id: "roses",
    name: "ROSES flowchart",
    category: "workflow",
    description: "R package and Shiny app for creating flow diagrams compliant with ROSES reporting standards.",
    url: "https://estech.shinyapps.io/roses_flowchart/",
    useInSynthesis: false,
    useInMetaAnalysis: false,
    useInReporting: true,
  },
  {
    id: "metafor",
    name: "metafor",
    category: "meta-analysis",
    description: "Comprehensive R package for conducting meta-analyses, providing functions for fixed, random, and mixed-effects models.",
    url: "https://www.metafor-project.org/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: true,
  },
  {
    id: "meta-r",
    name: "meta",
    category: "meta-analysis",
    description: "User-friendly R package for standard meta-analysis in clinical research, supporting binary, continuous, and diagnostic test accuracy data.",
    url: "https://cran.r-project.org/web/packages/meta/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: true,
  },
  {
    id: "forestplot",
    name: "forestplot",
    category: "visualization",
    description: "R package specifically designed for creating forest plots, standard visualizations in meta-analysis.",
    url: "https://cran.r-project.org/web/packages/forestplot/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: true,
  },
  {
    id: "openmee",
    name: "OpenMEE",
    category: "meta-analysis",
    description: "Open-source, cross-platform software for meta-analysis in ecology and evolution, graphical interface backed by metafor.",
    url: "https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.12708",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: true,
  },
  {
    id: "jasp",
    name: "JASP",
    category: "meta-analysis",
    description: "Free and open-source software for statistical analysis with a graphical interface and dedicated meta-analysis module.",
    url: "https://jasp-stats.org/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: true,
  },
  {
    id: "metaumbrella",
    name: "metaumbrella",
    category: "meta-analysis",
    description: "R package specifically designed to perform Umbrella Reviews, systematic reviews of multiple meta-analyses.",
    url: "https://metaumbrella.org",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: true,
  },
  {
    id: "netmeta",
    name: "netmeta",
    category: "meta-analysis",
    description: "R package for frequentist network meta-analysis using a graph-theoretical approach to estimate treatment effects.",
    url: "https://cran.r-project.org/web/packages/netmeta/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: true,
  },
  {
    id: "gemtc",
    name: "gemtc",
    category: "meta-analysis",
    description: "R package for Bayesian network meta-analysis using a Bayesian graphical model framework, primarily interfacing with JAGS.",
    url: "https://cran.r-project.org/web/packages/gemtc/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: true,
  },
  {
    id: "multinma",
    name: "multinma",
    category: "meta-analysis",
    description: "R package for network meta-analysis using Stan for Bayesian inference.",
    url: "https://cran.r-project.org/web/packages/multinma/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: true,
  },
  {
    id: "metasens",
    name: "metasens",
    category: "meta-analysis",
    description: "R package providing statistical methods for sensitivity analysis in meta-analysis, evaluating how sensitive results are to publication bias.",
    url: "https://cran.r-project.org/web/packages/metasens/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "robumeta",
    name: "robumeta",
    category: "meta-analysis",
    description: "R package for conducting robust variance estimation (RVE) in meta-analysis, handling dependent effect sizes.",
    url: "https://cran.r-project.org/web/packages/robumeta/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "meta4diag",
    name: "meta4diag",
    category: "meta-analysis",
    description: "R package designed for Bayesian meta-analysis of diagnostic test accuracy studies.",
    url: "https://cran.r-project.org/web/packages/meta4diag/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "mada",
    name: "mada",
    category: "meta-analysis",
    description: "R package providing functions for meta-analysis of diagnostic accuracy data, supporting hierarchical bivariate models.",
    url: "https://cran.r-project.org/web/packages/mada/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "diagmeta",
    name: "diagmeta",
    category: "meta-analysis",
    description: "R package used for meta-analysis of diagnostic accuracy studies with multiple thresholds, estimating summary ROC curves.",
    url: "https://cran.r-project.org/web/packages/diagmeta/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "metadta",
    name: "MetaDTA",
    category: "meta-analysis",
    description: "Web-based interactive tool for performing meta-analysis of diagnostic test accuracy studies using bivariate hierarchical models.",
    url: "https://crsu-metadta.le.ac.uk/MetaDTA/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "bamdit",
    name: "bamdit",
    category: "meta-analysis",
    description: "R package for Bayesian meta-analysis of diagnostic test data simplifying hierarchical models using JAGS.",
    url: "https://cran.r-project.org/package=bamdit",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "dosresmeta",
    name: "dosresmeta",
    category: "meta-analysis",
    description: "R package for performing dose-response meta-analysis of aggregated data using a one-stage approach.",
    url: "https://cran.r-project.org/web/packages/dosresmeta/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: true,
  },
  {
    id: "metasem",
    name: "metaSEM",
    category: "meta-analysis",
    description: "R package for conducting meta-analytic structural equation modeling (MASEM) to synthesize correlation or covariance matrices.",
    url: "https://cran.r-project.org/web/packages/metaSEM/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "robumeta",
    name: "robumeta",
    category: "meta-analysis",
    description: "R package for conducting robust variance estimation in meta-analysis, essential for handling dependent effect sizes.",
    url: "https://cran.r-project.org/web/packages/robumeta/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "clubsandwich",
    name: "clubSandwich",
    category: "meta-analysis",
    description: "R package providing cluster-robust variance estimators for models involving dependent effect sizes.",
    url: "https://cran.r-project.org/web/packages/clubSandwich/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "baggr",
    name: "baggr",
    category: "meta-analysis",
    description: "Bayesian meta-analysis of aggregated data using Stan, supporting hierarchical outcomes.",
    url: "https://cran.r-project.org/package=baggr",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: true,
  },
  {
    id: "bayesmeta",
    name: "bayesmeta",
    category: "meta-analysis",
    description: "R package for conducting Bayesian random-effects meta-analysis with focus on robust parameter estimation.",
    url: "https://cran.r-project.org/web/packages/bayesmeta/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: true,
  },
  {
    id: "metabma",
    name: "metaBMA",
    category: "meta-analysis",
    description: "Bayesian model averaging for random and fixed effects meta-analysis, comparing different meta-analytic models.",
    url: "https://cran.r-project.org/web/packages/metaBMA/",
    useInSynthesis: false,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "appraise",
    name: "appraise",
    category: "statistics",
    description: "Bias-aware evidence synthesis in systematic reviews, implementing a bias-aware framework.",
    url: "https://cran.r-project.org/package=appraise",
    useInSynthesis: true,
    useInMetaAnalysis: true,
    useInReporting: false,
  },
  {
    id: "vosviewer",
    name: "VOSviewer",
    category: "visualization",
    description: "Software tool for constructing and visualizing bibliometric networks, useful for evidence mapping.",
    url: "https://www.vosviewer.com/",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: true,
  },
  {
    id: "eviatlas",
    name: "EviAtlas",
    category: "visualization",
    description: "Tool for creating systematic map visualizations to organize and display the distribution of evidence.",
    url: "https://estech.shinyapps.io/eviatlas/",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: true,
  },
  {
    id: "gephi",
    name: "Gephi",
    category: "visualization",
    description: "Open-source platform for visualizing and exploring large networks and graphs, widely used for network analysis.",
    url: "https://gephi.org/",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: true,
  },
  {
    id: "cytoscape",
    name: "Cytoscape",
    category: "visualization",
    description: "Open source software platform for visualizing complex networks and integrating with attribute data.",
    url: "https://cytoscape.org/",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: true,
  },
  {
    id: "open-knowledge-maps",
    name: "Open Knowledge Maps",
    category: "visualization",
    description: "Open-source visual discovery tool creating knowledge maps by clustering top papers.",
    url: "https://openknowledgemaps.org/",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: true,
  },
  {
    id: "bibliometrix",
    name: "bibliometrix",
    category: "visualization",
    description: "Comprehensive tool for quantitative research in bibliometrics and scientometrics.",
    url: "http://www.bibliometrix.org/",
    useInSynthesis: true,
    useInMetaAnalysis: false,
    useInReporting: true,
  },
];

export const getToolsForSynthesis = (): EvidenceSynthesisTool[] =>
  EVIDENCE_SYNTHESIS_TOOLS.filter((t) => t.useInSynthesis);

export const getToolsForMetaAnalysis = (): EvidenceSynthesisTool[] =>
  EVIDENCE_SYNTHESIS_TOOLS.filter((t) => t.useInMetaAnalysis);

export const getToolsForReporting = (): EvidenceSynthesisTool[] =>
  EVIDENCE_SYNTHESIS_TOOLS.filter((t) => t.useInReporting);

export const getToolsByCategory = (category: EvidenceSynthesisTool["category"]): EvidenceSynthesisTool[] =>
  EVIDENCE_SYNTHESIS_TOOLS.filter((t) => t.category === category);

export const buildSynthesisToolReference = (): string => {
  const tools = getToolsForSynthesis();
  return tools.map((t) => `- [${t.name}](${t.url}) - ${t.description}`).join("\n");
};

export const buildMetaAnalysisToolReference = (): string => {
  const tools = getToolsForMetaAnalysis();
  return tools.map((t) => `- [${t.name}](${t.url}) - ${t.description}`).join("\n");
};

export const buildReportingToolReference = (): string => {
  const tools = getToolsForReporting();
  return tools.map((t) => `- [${t.name}](${t.url}) - ${t.description}`).join("\n");
};
