export const REPORTING_GUIDELINES = {
  overview: `Reporting guidelines are evidence-based recommendations for what information should be included when reporting specific types of research studies. They provide checklists and flow diagrams to ensure complete, accurate, and transparent reporting. The EQUATOR Network maintains a comprehensive library of reporting guidelines.`,

  byStudyType: {
    "Randomized controlled trial": {
      guideline: "CONSORT",
      fullName: "Consolidated Standards of Reporting Trials",
      version: "CONSORT 2010",
      url: "http://www.consort-statement.org/",
      checklistItems: [
        "Title identifies study as randomized trial",
        "Structured abstract",
        "Scientific background and rationale",
        "Specific objectives and hypotheses",
        "Trial design description (parallel, crossover, factorial, etc.)",
        "Eligibility criteria for participants",
        "Settings and locations of data collection",
        "Interventions described in sufficient detail for replication",
        "Primary and secondary outcomes defined",
        "Sample size determination and power calculation",
        "Randomization sequence generation",
        "Allocation concealment mechanism",
        "Blinding implementation",
        "Statistical methods",
        "Participant flow with reasons for dropouts",
        "Recruitment dates and follow-up dates",
        "Baseline characteristics table",
        "Analysis results for each outcome",
        "Harms and adverse events",
        "Trial limitations",
        "Generalizability",
        "Interpretation consistent with results",
        "Trial registration number",
        "Full protocol access",
        "Funding sources",
      ],
      extensions: [
        "CONSORT for cluster randomized trials",
        "CONSORT for non-inferiority and equivalence trials",
        "CONSORT for pragmatic trials",
        "CONSORT for crossover trials",
        "CONSORT for N-of-1 trials",
        "CONSORT for stepped wedge designs",
      ],
    },
    "Cohort study": {
      guideline: "STROBE",
      fullName: "Strengthening the Reporting of Observational Studies in Epidemiology",
      version: "STROBE 2007",
      url: "https://www.strobe-statement.org/",
      checklistItems: [
        "Title and abstract indicate study design",
        "Background and rationale",
        "Objectives",
        "Study design with rationale",
        "Setting, locations, and dates",
        "Eligibility criteria and selection methods",
        "Variables clearly defined (outcomes, exposures, confounders)",
        "Data sources and measurement methods",
        "Bias management strategies",
        "Study size justification",
        "Handling of quantitative variables",
        "Statistical methods including confounding and interactions",
        "Sensitivity analyses",
        "Participant flow with reasons for non-participation",
        "Descriptive data including follow-up time",
        "Outcome data",
        "Main results with unadjusted and adjusted estimates",
        "Other analyses (subgroups, sensitivity analyses)",
        "Key results summary",
        "Limitations with potential bias discussion",
        "Interpretation and generalizability",
        "Funding sources and role",
      ],
      extensions: [
        "STROBE-ME (Molecular Epidemiology)",
        "RECORD (Routinely collected health data)",
        "STROBE-RDS (Respondent-driven sampling)",
      ],
    },
    "Case-control study": {
      guideline: "STROBE",
      fullName: "Strengthening the Reporting of Observational Studies in Epidemiology",
      version: "STROBE 2007",
      url: "https://www.strobe-statement.org/",
      checklistItems: [
        "Title and abstract indicate study design",
        "Background and rationale",
        "Objectives",
        "Study design with rationale",
        "Setting, locations, and dates",
        "Eligibility criteria and selection methods",
        "Variables clearly defined (outcomes, exposures, confounders)",
        "Data sources and measurement methods",
        "Bias management strategies",
        "Study size justification",
        "Handling of quantitative variables",
        "Statistical methods including confounding and interactions",
        "Sensitivity analyses",
        "Participant flow with reasons for non-participation",
        "Descriptive data including follow-up time",
        "Outcome data",
        "Main results with unadjusted and adjusted estimates",
        "Other analyses (subgroups, sensitivity analyses)",
        "Key results summary",
        "Limitations with potential bias discussion",
        "Interpretation and generalizability",
        "Funding sources and role",
      ],
    },
    "Cross-sectional study": {
      guideline: "STROBE",
      fullName: "Strengthening the Reporting of Observational Studies in Epidemiology",
      version: "STROBE 2007",
      url: "https://www.strobe-statement.org/",
      checklistItems: [
        "Title and abstract indicate study design",
        "Background and rationale",
        "Objectives",
        "Study design with rationale",
        "Setting, locations, and dates",
        "Eligibility criteria and selection methods",
        "Variables clearly defined (outcomes, exposures, confounders)",
        "Data sources and measurement methods",
        "Bias management strategies",
        "Study size justification",
        "Handling of quantitative variables",
        "Statistical methods including confounding and interactions",
        "Sensitivity analyses",
        "Participant flow with reasons for non-participation",
        "Descriptive data",
        "Outcome data",
        "Main results with unadjusted and adjusted estimates",
        "Other analyses (subgroups, sensitivity analyses)",
        "Key results summary",
        "Limitations with potential bias discussion",
        "Interpretation and generalizability",
        "Funding sources and role",
      ],
    },
    "Systematic review": {
      guideline: "PRISMA",
      fullName: "Preferred Reporting Items for Systematic Reviews and Meta-Analyses",
      version: "PRISMA 2020",
      url: "http://www.prisma-statement.org/",
      checklistItems: [
        "Title identifies as systematic review/meta-analysis",
        "Structured abstract",
        "Introduction: Rationale and objectives",
        "Eligibility criteria",
        "Information sources (databases, dates)",
        "Search strategy (full strategy for at least one database)",
        "Selection process",
        "Data collection process",
        "Data items extracted",
        "Risk of bias assessment",
        "Effect measures",
        "Synthesis methods",
        "Reporting bias assessment",
        "Certainty assessment (e.g., GRADE)",
        "Study selection flow diagram",
        "Study characteristics",
        "Risk of bias assessment results",
        "Synthesis results (meta-analysis if applicable)",
        "Reporting biases",
        "Certainty of evidence",
        "Limitations",
        "Interpretation",
        "Implications",
      ],
      extensions: [
        "PRISMA for Abstracts",
        "PRISMA for Protocols (PRISMA-P)",
        "PRISMA for Network Meta-Analyses",
        "PRISMA for Scoping Reviews (PRISMA-ScR)",
        "PRISMA for Individual Patient Data",
        "PRISMA for Diagnostic Test Accuracy",
        "PRISMA for Equity-focused reviews",
      ],
    },
    "Meta-analysis": {
      guideline: "PRISMA",
      fullName: "Preferred Reporting Items for Systematic Reviews and Meta-Analyses",
      version: "PRISMA 2020",
      url: "http://www.prisma-statement.org/",
      checklistItems: [
        "Title identifies as systematic review/meta-analysis",
        "Structured abstract",
        "Introduction: Rationale and objectives",
        "Eligibility criteria",
        "Information sources (databases, dates)",
        "Search strategy (full strategy for at least one database)",
        "Selection process",
        "Data collection process",
        "Data items extracted",
        "Risk of bias assessment",
        "Effect measures",
        "Synthesis methods",
        "Reporting bias assessment",
        "Certainty assessment (e.g., GRADE)",
        "Study selection flow diagram",
        "Study characteristics",
        "Risk of bias assessment results",
        "Synthesis results (meta-analysis)",
        "Reporting biases",
        "Certainty of evidence",
        "Limitations",
        "Interpretation",
        "Implications",
      ],
    },
    "Clinical trial protocol": {
      guideline: "SPIRIT",
      fullName: "Standard Protocol Items: Recommendations for Interventional Trials",
      version: "SPIRIT 2013",
      url: "https://www.spirit-statement.org/",
      checklistItems: [
        "Administrative information (title, trial registration, funding)",
        "Introduction (background, rationale, objectives)",
        "Methods: Trial design",
        "Study setting",
        "Eligibility criteria",
        "Interventions in detail",
        "Outcomes (primary and secondary)",
        "Participant timeline",
        "Sample size calculation",
        "Recruitment strategy",
        "Allocation and randomization",
        "Blinding",
        "Data collection methods",
        "Data management",
        "Statistical methods",
        "Monitoring (data monitoring committee)",
        "Harms reporting",
        "Auditing",
        "Ethics and dissemination",
        "Ethics approval",
        "Consent procedures",
        "Confidentiality",
        "Dissemination plans",
      ],
    },
    "Diagnostic accuracy study": {
      guideline: "STARD",
      fullName: "Standards for Reporting of Diagnostic Accuracy Studies",
      version: "STARD 2015",
      url: "https://www.equator-network.org/reporting-guidelines/stard/",
      checklistItems: [
        "Study design identification",
        "Background information and objectives",
        "Study design description",
        "Participant selection criteria and recruitment",
        "Data collection methods",
        "Index test description and execution",
        "Reference standard description",
        "Rationale for choosing reference standard",
        "Test result definition and cutoffs",
        "Flow of participants with timing",
        "Baseline demographic and clinical characteristics",
        "Cross-tabulation of index test results by reference standard",
        "Estimates of diagnostic accuracy with confidence intervals",
        "Handling of indeterminate results",
        "Adverse events from testing",
      ],
    },
    "Prediction model study": {
      guideline: "TRIPOD",
      fullName: "Transparent Reporting of a multivariable prediction model for Individual Prognosis Or Diagnosis",
      version: "TRIPOD 2015",
      url: "https://www.tripod-statement.org/",
      checklistItems: [
        "Title identifies study as prediction model study",
        "Abstract summarizes key elements",
        "Background and objectives",
        "Data source and participants",
        "Outcome definition",
        "Predictors (candidate and selected)",
        "Sample size justification",
        "Missing data handling",
        "Model building procedure",
        "Model specification (equation or algorithm)",
        "Model performance measures",
        "Risk groups if used",
        "Participant flow diagram",
        "Model development results",
        "Model performance",
        "Model updating if applicable",
      ],
    },
    "Animal study": {
      guideline: "ARRIVE",
      fullName: "Animal Research: Reporting of In Vivo Experiments",
      version: "ARRIVE 2.0 (2020)",
      url: "https://arriveguidelines.org/",
      essentialItems: [
        "Study design",
        "Sample size calculation",
        "Inclusion and exclusion criteria",
        "Randomization",
        "Blinding",
        "Outcome measures",
        "Statistical methods",
        "Experimental animals (species, strain, sex, age)",
        "Experimental procedures",
        "Results and interpretation",
      ],
      recommendedItems: [
        "Abstract, background, objectives",
        "Ethics statement",
        "Housing and husbandry",
        "Animal care and monitoring",
        "Interpretation and generalizability",
        "Protocol registration",
        "Data access",
      ],
    },
    "Case report": {
      guideline: "CARE",
      fullName: "CAse REport Guidelines",
      version: "CARE 2013",
      url: "https://www.care-statement.org/",
      checklistItems: [
        "Title with 'case report'",
        "Abstract summarizing case",
        "Introduction with case background",
        "Patient information (demographics, primary concern)",
        "Clinical findings",
        "Timeline of events",
        "Diagnostic assessment",
        "Therapeutic intervention",
        "Follow-up and outcomes",
        "Discussion with strengths and limitations",
        "Patient perspective",
        "Informed consent",
      ],
    },
    "Quality improvement study": {
      guideline: "SQUIRE",
      fullName: "Standards for QUality Improvement Reporting Excellence",
      version: "SQUIRE 2.0 (2015)",
      url: "http://www.squire-statement.org/",
      checklistItems: [
        "Title and abstract",
        "Introduction (problem description, available knowledge, rationale, objectives)",
        "Methods (context, intervention, study design, measures, analysis, ethical review)",
        "Results (intervention, outcomes)",
        "Discussion (summary, interpretation, limitations, conclusions)",
        "Other information (funding)",
      ],
    },
    "Economic evaluation": {
      guideline: "CHEERS",
      fullName: "Consolidated Health Economic Evaluation Reporting Standards",
      version: "CHEERS 2022",
      url: "https://www.equator-network.org/reporting-guidelines/cheers/",
      checklistItems: [
        "Title identification as economic evaluation",
        "Abstract",
        "Background and objectives",
        "Target population and subgroups",
        "Setting and location",
        "Study perspective",
        "Comparators",
        "Time horizon",
        "Discount rate",
        "Selection of outcomes",
        "Measurement of effectiveness",
        "Measurement and valuation of costs",
        "Currency and price adjustments",
        "Choice of model",
        "Assumptions",
        "Analytical methods",
      ],
    },
    "Qualitative research": {
      guideline: "SRQR",
      fullName: "Standards for Reporting Qualitative Research",
      version: "SRQR 2014",
      url: "https://www.equator-network.org/reporting-guidelines/srqr/",
      checklistItems: [
        "Title and abstract",
        "Introduction (problem formulation, purpose)",
        "Methods (qualitative approach, researcher characteristics, context, sampling strategy, ethical issues, data collection, data analysis, trustworthiness)",
        "Results (synthesis and interpretation, links to empirical data)",
        "Discussion (limitations, implications)",
      ],
      alternative: "COREQ (Consolidated criteria for reporting qualitative research) for interviews and focus groups",
    },
  },

  getGuidelineForStudyType(studyType: string): { guideline: string; fullName: string; version: string; url: string; checklistItems: string[] } | null {
    const normalized = studyType.toLowerCase();
    for (const [key, value] of Object.entries(REPORTING_GUIDELINES.byStudyType)) {
      if (normalized.includes(key.toLowerCase()) || key.toLowerCase().includes(normalized)) {
        return value as any;
      }
    }
    return null;
  },

  getGuidelineAdherenceStatement(studyType: string): string {
    const guideline = REPORTING_GUIDELINES.getGuidelineForStudyType(studyType);
    if (!guideline) return "";
    return `This study is reported in accordance with the ${guideline.fullName} (${guideline.guideline}) statement. A completed checklist is provided as Supplementary File 1.`;
  },

  getChecklistAsMarkdown(studyType: string): string {
    const guideline = REPORTING_GUIDELINES.getGuidelineForStudyType(studyType);
    if (!guideline) return "";

    let md = `## ${guideline.guideline} Reporting Guideline Checklist\n\n`;
    md += `**Guideline:** ${guideline.fullName}\n`;
    md += `**Version:** ${guideline.version}\n`;
    md += `**Reference:** ${guideline.url}\n\n`;
    md += `| # | Checklist Item | Page/Line |\n|---|----------------|----------|\n`;

    const items = (guideline as any).checklistItems || (guideline as any).essentialItems || [];
    items.forEach((item: string, idx: number) => {
      md += `| ${idx + 1} | ${item} | |\n`;
    });

    md += `\n**Note:** Complete the Page/Line column before submission.`;
    return md;
  },

  getMethodsStatement(studyType: string): string {
    const guideline = REPORTING_GUIDELINES.getGuidelineForStudyType(studyType);
    if (!guideline) return "";
    return `This study is reported in accordance with the ${guideline.fullName} (${guideline.guideline}) statement. A completed ${guideline.guideline} checklist is provided as Supplementary File 1.`;
  },
};
