"use client";

import React, { useState } from "react";
import { Sparkles, ChevronRight, Download, FlaskConical, FileText, Info } from "lucide-react";
import { useApp } from "@/context/AppContext";

const FUNDERS = [
  "NIH (R01, R21, K-series)",
  "Wellcome Trust",
  "Bill & Melinda Gates Foundation",
  "EU Horizon Europe",
  "WHO Research Grants",
  "NIH (India) — DBT / ICMR / DST",
  "UKRI / MRC",
  "African Academy of Sciences",
  "Fogarty International Center",
  "Custom / Other",
];

const generateMockGrantProposal = (state: any): string => {
  const title = state.userTitleInput || state.aimObjectives.aim
    ? state.userTitleInput || "Implementation and Cost-Effectiveness of Annual IGRA-Based LTBI Screening Among Healthcare Workers"
    : "Research Study";

  const aim = state.aimObjectives.aim || "To evaluate the implementation and cost-effectiveness of an annual IGRA-based LTBI screening program for HCWs in tertiary care hospitals.";

  return `GRANT PROPOSAL DRAFT
====================
Generated by Resilient Research Assistant — Funder-tailored template

A. PROJECT OVERVIEW
--------------------
Title: ${title}

Principal Investigator: [To be assigned — specify here]
Co-Investigators: [Add co-investigators with role descriptions]
Institution: [Host institution, department, address]
Proposed Duration: 36 months
Total Requested Budget: USD $1,240,000 (direct + indirect @ 30%)

B. ABSTRACT / SUMMARY
----------------------
${aim.substring(0, 300)}${aim.length > 300 ? "..." : ""}

This proposal addresses a critical evidence and implementation gap in latent tuberculosis infection (LTBI) screening for healthcare workers (HCWs) in low- and middle-income countries. We request funding to support a mixed-methods cluster RCT evaluating annual IGRA-based screening augmented by digital health tools compared with standard triennial TST screening. Expected outputs include 4–6 peer-reviewed publications, a national policy brief, and a training package scalable across the African region.

C. SPECIFIC AIMS
-----------------
Aim 1 (Primary): To compare the implementation effectiveness and cost-effectiveness of annual IGRA-based screening versus standard TST in tertiary hospital settings.

Aim 2: To evaluate digital health tool (SMS reminders) impact on IPT completion rates compared with no-reminder standard care.

Aim 3: To conduct a qualitative process evaluation identifying barriers and enablers of program implementation at facility and individual levels.

D. INNOVATION & SIGNIFICANCE
------------------------------
• First multi-site cRCT of IGRA screening in Nigerian tertiary hospitals with embedded economic and qualitative components.
• Digital reminder platform integrated with national health ID system.
• Open-access data repository deposition planned within 12 months of publication.

E. APPROACH / METHODOLOGY
----------------------------
Study Design: Mixed-methods sequential explanatory (cRCT + qualitative PE).

Setting: 8 tertiary hospitals (4 intervention, 4 control) across Lagos and Abuja.

Population: N=3,200 currently employed HCWs with direct patient contact ≥6 months.

Intervention: Annual workplace IGRA (QFT-Plus) + SMS for IPT appointment reminders.

Comparator: Standard annual TST with physician reading at 48–72 hours.

Primary Outcome: LTBI conversion rate at 12 months.

Sample Size: n=384 per arm, total 768 (5% loss adjustment).

Analysis: Mixed-effects logistic regression (ITT); NVivo thematic analysis; cost-effectiveness from MoH perspective.

F. EXPECTED OUTCOMES & DELIVERABLES
--------------------------------------
1. Peer-reviewed publications: ≥4 (IJTLD, PLOS Medicine, cost-effectiveness journal, implementation science journal)
2. Policy brief: 2-page digest for Nigeria NTLCP and WHO AFRO
3. Training package: 8 CPD-accredited e-learning modules
4. Sensitized dataset: Harvard Dataverse (CC-BY-4.0)
5. Health systems advisory note: Annual debrief to MoH

G. INVESTIGATOR TEAM & TRACK RECORD
--------------------------------------
[Insert CVs / biosketches here — prompt: PI has led previous WHO-cofunded TB contact tracing trials in 3 countries.]

H. BUDGET NARRATIVE (SUMMARY)
-------------------------------
| Category            | Year 1   | Year 2   | Year 3   | Total     |
|---------------------|----------|----------|----------|-----------|
| Personnel           | $210,000 | $220,000 | $230,000 | $660,000  |
| Equipment (IGRA)    | $95,000  | $95,000  | $95,000  | $285,000  |
| Digital intervention| $35,000  | $25,000  | $15,000  | $75,000   |
| Training/dissem.    | $40,000  | $50,000  | $55,000  | $145,000  |
| Overhead (30%)      | $66,000  | $66,000  | $66,000  | $198,000  |
|---------------------|----------|----------|----------|-----------|
| TOTAL               | $446,000 | $456,000 | $461,000 | $1,363,000|

I. HUMAN SUBJECTS / ETHICS
----------------------------
IRB Approval: Institutional Review Board, [Institution] — Protocol #[to be assigned].
Informed Consent: Written + verbal for illiterate; witnessed consent.
Data Safety: DSMB with 3 independent members; quarterly SAE reporting.

J. TIMELINE
------------
Month 1–3: IRB + training + readiness
Month 4–6: Baseline screening Wave 1
Month 7–24: Bi-annual Waves 2–5 + digital reminder phase
Month 25–30: Analysis + drafting
Month 31–36: Dissemination + final report

K. LETTERS OF SUPPORT
----------------------
[Include institutional commitment letters, MoH endorsement, stakeholder CAB support]

---

Proposal last updated: ${new Date().toISOString()}
This is a system-generated draft — please review and revise all bracketed sections before submission.
`;
};

export default function GrantWritingTab() {
  const { state } = useApp();
  const [selectedFunder, setSelectedFunder] = useState(FUNDERS[0]);
  const [proposal, setProposal] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);

  const handleGenerate = async () => {
    setIsGenerating(true);
    setProposal("");
    await new Promise((r) => setTimeout(r, 2500));
    const generated = generateMockGrantProposal(state);
    setProposal(generated);
    setIsGenerating(false);
  };

  const handleAutoImport = () => {
    alert(
      "Auto-imported from research pipeline:\n" +
        `• Title: ${state.userTitleInput || "(from Step 7)"}\n` +
        `• Aim: ${state.aimObjectives.aim || "(from Step 8)"}\n` +
        `• Objective: ${state.aimObjectives.primaryObjective || "(from Step 8)"}\n` +
        `• Methodology: ${state.methodology.studySite || "(from Step 9)"}\n\n` +
        "All sections now pre-filled in proposal editor."
    );
  };

  return (
    <div className="space-y-6">
      <div className="bg-[#0d1b3e] border border-blue-900/50 rounded-lg p-6 shadow">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="text-xl font-bold text-white">Grant Writing</h2>
            <p className="text-sm text-blue-300">
              Auto-generated grant proposal with sections imported directly from your research pipeline.
            </p>
          </div>
          <button
            onClick={handleAutoImport}
            className="text-sm bg-blue-900/50 text-blue-200 px-4 py-2 rounded-lg hover:bg-blue-900/70 flex items-center gap-1"
          >
            <Info size={14} />
            Auto-Import Pipeline Data
          </button>
        </div>

        <div className="flex flex-wrap items-center gap-4 mb-6">
          <div className="relative">
            <select
              value={selectedFunder}
              onChange={(e) => setSelectedFunder(e.target.value)}
              className="appearance-none bg-blue-950 border border-blue-800 text-white rounded-lg pl-4 pr-10 py-2.5 text-sm"
            >
              {FUNDERS.map((f) => (
                <option key={f} value={f}>{f}</option>
              ))}
            </select>
            <ChevronRight size={12} className="absolute right-3 top-1/2 -translate-y-1/2 text-blue-400 rotate-[-90deg] pointer-events-none" />
          </div>

          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="bg-yellow-500 hover:bg-yellow-600 text-[#0a1a3a] font-bold px-6 py-2.5 rounded-lg disabled:opacity-50 flex items-center gap-2"
          >
            <Sparkles size={16} />
            {isGenerating ? "Generating Proposal..." : "Generate Grant Proposal"}
          </button>

          {proposal && (
            <div className="relative ml-auto">
              <button
                onClick={() => setShowExportMenu(!showExportMenu)}
                className="bg-green-900/50 text-green-300 px-4 py-2 rounded-lg hover:bg-green-900/70 flex items-center gap-2 text-sm"
              >
                <Download size={14} />
                Export
              </button>
              {showExportMenu && (
                <div className="absolute right-0 top-full mt-1 bg-[#0a1530] border border-blue-800 rounded-lg shadow-lg overflow-hidden z-10 w-48">
                  <button
                    onClick={() => { alert('Exporting as Word (.docx) for ' + selectedFunder); setShowExportMenu(false); }}
                    className="w-full text-left px-4 py-2 text-sm text-white hover:bg-blue-900/50 flex items-center gap-2"
                  >
                    <FileText size={14} /> Export as Word
                  </button>
                  <button
                    onClick={() => { alert("Exporting grant proposal as PDF..."); setShowExportMenu(false); }}
                    className="w-full text-left px-4 py-2 text-sm text-white hover:bg-blue-900/50 flex items-center gap-2"
                  >
                    <Download size={14} /> Export as PDF
                  </button>
                </div>
              )}
            </div>
          )}
        </div>

        {isGenerating && (
          <div className="flex items-center justify-center py-16">
            <div className="text-center">
              <div className="w-10 h-10 border-4 border-yellow-400 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
              <p className="text-blue-200 text-sm">Composing grant proposal sections...</p>
              <p className="text-blue-400 text-xs mt-1">Tailoring to {selectedFunder} format</p>
            </div>
          </div>
        )}

        {!isGenerating && !proposal && (
          <div className="text-center py-16 text-blue-400">
            <FlaskConical size={40} className="mx-auto mb-3 opacity-50" />
            <p className="text-sm">Select a funder and generate a tailored grant proposal draft pre-populated from your pipeline.</p>
          </div>
        )}

        {proposal && !isGenerating && (
          <div>
            <div className="bg-blue-950/50 border border-blue-900 rounded-lg p-5 max-h-[600px] overflow-y-auto">
              <pre className="text-sm text-blue-100 whitespace-pre-wrap font-mono leading-relaxed">{proposal}</pre>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
